name: 'CI'

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Yarn version
        run: yarn --version
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn run tree-sitter test
